# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/UHUB_DC/uhub

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/UHUB_DC/uhub

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/UHUB_DC/uhub/CMakeFiles /home/user/UHUB_DC/uhub/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/UHUB_DC/uhub/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mod_logging

# Build rule for target.
mod_logging: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mod_logging
.PHONY : mod_logging

# fast build rule for target.
mod_logging/fast:
	$(MAKE) -f CMakeFiles/mod_logging.dir/build.make CMakeFiles/mod_logging.dir/build
.PHONY : mod_logging/fast

#=============================================================================
# Target rules for targets named mod_welcome

# Build rule for target.
mod_welcome: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mod_welcome
.PHONY : mod_welcome

# fast build rule for target.
mod_welcome/fast:
	$(MAKE) -f CMakeFiles/mod_welcome.dir/build.make CMakeFiles/mod_welcome.dir/build
.PHONY : mod_welcome/fast

#=============================================================================
# Target rules for targets named mod_example

# Build rule for target.
mod_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mod_example
.PHONY : mod_example

# fast build rule for target.
mod_example/fast:
	$(MAKE) -f CMakeFiles/mod_example.dir/build.make CMakeFiles/mod_example.dir/build
.PHONY : mod_example/fast

#=============================================================================
# Target rules for targets named mod_topic

# Build rule for target.
mod_topic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mod_topic
.PHONY : mod_topic

# fast build rule for target.
mod_topic/fast:
	$(MAKE) -f CMakeFiles/mod_topic.dir/build.make CMakeFiles/mod_topic.dir/build
.PHONY : mod_topic/fast

#=============================================================================
# Target rules for targets named mod_auth_simple

# Build rule for target.
mod_auth_simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mod_auth_simple
.PHONY : mod_auth_simple

# fast build rule for target.
mod_auth_simple/fast:
	$(MAKE) -f CMakeFiles/mod_auth_simple.dir/build.make CMakeFiles/mod_auth_simple.dir/build
.PHONY : mod_auth_simple/fast

#=============================================================================
# Target rules for targets named mod_auth_sqlite

# Build rule for target.
mod_auth_sqlite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mod_auth_sqlite
.PHONY : mod_auth_sqlite

# fast build rule for target.
mod_auth_sqlite/fast:
	$(MAKE) -f CMakeFiles/mod_auth_sqlite.dir/build.make CMakeFiles/mod_auth_sqlite.dir/build
.PHONY : mod_auth_sqlite/fast

#=============================================================================
# Target rules for targets named autotest-bin

# Build rule for target.
autotest-bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autotest-bin
.PHONY : autotest-bin

# fast build rule for target.
autotest-bin/fast:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/build
.PHONY : autotest-bin/fast

#=============================================================================
# Target rules for targets named adc

# Build rule for target.
adc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adc
.PHONY : adc

# fast build rule for target.
adc/fast:
	$(MAKE) -f CMakeFiles/adc.dir/build.make CMakeFiles/adc.dir/build
.PHONY : adc/fast

#=============================================================================
# Target rules for targets named mod_chat_history

# Build rule for target.
mod_chat_history: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mod_chat_history
.PHONY : mod_chat_history

# fast build rule for target.
mod_chat_history/fast:
	$(MAKE) -f CMakeFiles/mod_chat_history.dir/build.make CMakeFiles/mod_chat_history.dir/build
.PHONY : mod_chat_history/fast

#=============================================================================
# Target rules for targets named uhub

# Build rule for target.
uhub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uhub
.PHONY : uhub

# fast build rule for target.
uhub/fast:
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/build
.PHONY : uhub/fast

#=============================================================================
# Target rules for targets named mod_chat_history_sqlite

# Build rule for target.
mod_chat_history_sqlite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mod_chat_history_sqlite
.PHONY : mod_chat_history_sqlite

# fast build rule for target.
mod_chat_history_sqlite/fast:
	$(MAKE) -f CMakeFiles/mod_chat_history_sqlite.dir/build.make CMakeFiles/mod_chat_history_sqlite.dir/build
.PHONY : mod_chat_history_sqlite/fast

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named adcclient

# Build rule for target.
adcclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adcclient
.PHONY : adcclient

# fast build rule for target.
adcclient/fast:
	$(MAKE) -f CMakeFiles/adcclient.dir/build.make CMakeFiles/adcclient.dir/build
.PHONY : adcclient/fast

#=============================================================================
# Target rules for targets named mod_chat_only

# Build rule for target.
mod_chat_only: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mod_chat_only
.PHONY : mod_chat_only

# fast build rule for target.
mod_chat_only/fast:
	$(MAKE) -f CMakeFiles/mod_chat_only.dir/build.make CMakeFiles/mod_chat_only.dir/build
.PHONY : mod_chat_only/fast

#=============================================================================
# Target rules for targets named network

# Build rule for target.
network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 network
.PHONY : network

# fast build rule for target.
network/fast:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/build
.PHONY : network/fast

#=============================================================================
# Target rules for targets named mod_no_guest_downloads

# Build rule for target.
mod_no_guest_downloads: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mod_no_guest_downloads
.PHONY : mod_no_guest_downloads

# fast build rule for target.
mod_no_guest_downloads/fast:
	$(MAKE) -f CMakeFiles/mod_no_guest_downloads.dir/build.make CMakeFiles/mod_no_guest_downloads.dir/build
.PHONY : mod_no_guest_downloads/fast

#=============================================================================
# Target rules for targets named uhub-admin

# Build rule for target.
uhub-admin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uhub-admin
.PHONY : uhub-admin

# fast build rule for target.
uhub-admin/fast:
	$(MAKE) -f CMakeFiles/uhub-admin.dir/build.make CMakeFiles/uhub-admin.dir/build
.PHONY : uhub-admin/fast

#=============================================================================
# Target rules for targets named uhub-passwd

# Build rule for target.
uhub-passwd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uhub-passwd
.PHONY : uhub-passwd

# fast build rule for target.
uhub-passwd/fast:
	$(MAKE) -f CMakeFiles/uhub-passwd.dir/build.make CMakeFiles/uhub-passwd.dir/build
.PHONY : uhub-passwd/fast

autotest/test.o: autotest/test.c.o

.PHONY : autotest/test.o

# target to build an object file
autotest/test.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/autotest/test.c.o
.PHONY : autotest/test.c.o

autotest/test.i: autotest/test.c.i

.PHONY : autotest/test.i

# target to preprocess a source file
autotest/test.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/autotest/test.c.i
.PHONY : autotest/test.c.i

autotest/test.s: autotest/test.c.s

.PHONY : autotest/test.s

# target to generate assembly for a file
autotest/test.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/autotest/test.c.s
.PHONY : autotest/test.c.s

src/adc/message.o: src/adc/message.c.o

.PHONY : src/adc/message.o

# target to build an object file
src/adc/message.c.o:
	$(MAKE) -f CMakeFiles/adc.dir/build.make CMakeFiles/adc.dir/src/adc/message.c.o
.PHONY : src/adc/message.c.o

src/adc/message.i: src/adc/message.c.i

.PHONY : src/adc/message.i

# target to preprocess a source file
src/adc/message.c.i:
	$(MAKE) -f CMakeFiles/adc.dir/build.make CMakeFiles/adc.dir/src/adc/message.c.i
.PHONY : src/adc/message.c.i

src/adc/message.s: src/adc/message.c.s

.PHONY : src/adc/message.s

# target to generate assembly for a file
src/adc/message.c.s:
	$(MAKE) -f CMakeFiles/adc.dir/build.make CMakeFiles/adc.dir/src/adc/message.c.s
.PHONY : src/adc/message.c.s

src/adc/sid.o: src/adc/sid.c.o

.PHONY : src/adc/sid.o

# target to build an object file
src/adc/sid.c.o:
	$(MAKE) -f CMakeFiles/mod_logging.dir/build.make CMakeFiles/mod_logging.dir/src/adc/sid.c.o
	$(MAKE) -f CMakeFiles/adc.dir/build.make CMakeFiles/adc.dir/src/adc/sid.c.o
.PHONY : src/adc/sid.c.o

src/adc/sid.i: src/adc/sid.c.i

.PHONY : src/adc/sid.i

# target to preprocess a source file
src/adc/sid.c.i:
	$(MAKE) -f CMakeFiles/mod_logging.dir/build.make CMakeFiles/mod_logging.dir/src/adc/sid.c.i
	$(MAKE) -f CMakeFiles/adc.dir/build.make CMakeFiles/adc.dir/src/adc/sid.c.i
.PHONY : src/adc/sid.c.i

src/adc/sid.s: src/adc/sid.c.s

.PHONY : src/adc/sid.s

# target to generate assembly for a file
src/adc/sid.c.s:
	$(MAKE) -f CMakeFiles/mod_logging.dir/build.make CMakeFiles/mod_logging.dir/src/adc/sid.c.s
	$(MAKE) -f CMakeFiles/adc.dir/build.make CMakeFiles/adc.dir/src/adc/sid.c.s
.PHONY : src/adc/sid.c.s

src/core/auth.o: src/core/auth.c.o

.PHONY : src/core/auth.o

# target to build an object file
src/core/auth.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/auth.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/auth.c.o
.PHONY : src/core/auth.c.o

src/core/auth.i: src/core/auth.c.i

.PHONY : src/core/auth.i

# target to preprocess a source file
src/core/auth.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/auth.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/auth.c.i
.PHONY : src/core/auth.c.i

src/core/auth.s: src/core/auth.c.s

.PHONY : src/core/auth.s

# target to generate assembly for a file
src/core/auth.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/auth.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/auth.c.s
.PHONY : src/core/auth.c.s

src/core/command_parser.o: src/core/command_parser.c.o

.PHONY : src/core/command_parser.o

# target to build an object file
src/core/command_parser.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/command_parser.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/command_parser.c.o
.PHONY : src/core/command_parser.c.o

src/core/command_parser.i: src/core/command_parser.c.i

.PHONY : src/core/command_parser.i

# target to preprocess a source file
src/core/command_parser.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/command_parser.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/command_parser.c.i
.PHONY : src/core/command_parser.c.i

src/core/command_parser.s: src/core/command_parser.c.s

.PHONY : src/core/command_parser.s

# target to generate assembly for a file
src/core/command_parser.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/command_parser.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/command_parser.c.s
.PHONY : src/core/command_parser.c.s

src/core/commands.o: src/core/commands.c.o

.PHONY : src/core/commands.o

# target to build an object file
src/core/commands.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/commands.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/commands.c.o
.PHONY : src/core/commands.c.o

src/core/commands.i: src/core/commands.c.i

.PHONY : src/core/commands.i

# target to preprocess a source file
src/core/commands.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/commands.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/commands.c.i
.PHONY : src/core/commands.c.i

src/core/commands.s: src/core/commands.c.s

.PHONY : src/core/commands.s

# target to generate assembly for a file
src/core/commands.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/commands.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/commands.c.s
.PHONY : src/core/commands.c.s

src/core/config.o: src/core/config.c.o

.PHONY : src/core/config.o

# target to build an object file
src/core/config.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/config.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/config.c.o
.PHONY : src/core/config.c.o

src/core/config.i: src/core/config.c.i

.PHONY : src/core/config.i

# target to preprocess a source file
src/core/config.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/config.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/config.c.i
.PHONY : src/core/config.c.i

src/core/config.s: src/core/config.c.s

.PHONY : src/core/config.s

# target to generate assembly for a file
src/core/config.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/config.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/config.c.s
.PHONY : src/core/config.c.s

src/core/eventqueue.o: src/core/eventqueue.c.o

.PHONY : src/core/eventqueue.o

# target to build an object file
src/core/eventqueue.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/eventqueue.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/eventqueue.c.o
.PHONY : src/core/eventqueue.c.o

src/core/eventqueue.i: src/core/eventqueue.c.i

.PHONY : src/core/eventqueue.i

# target to preprocess a source file
src/core/eventqueue.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/eventqueue.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/eventqueue.c.i
.PHONY : src/core/eventqueue.c.i

src/core/eventqueue.s: src/core/eventqueue.c.s

.PHONY : src/core/eventqueue.s

# target to generate assembly for a file
src/core/eventqueue.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/eventqueue.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/eventqueue.c.s
.PHONY : src/core/eventqueue.c.s

src/core/hub.o: src/core/hub.c.o

.PHONY : src/core/hub.o

# target to build an object file
src/core/hub.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/hub.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/hub.c.o
.PHONY : src/core/hub.c.o

src/core/hub.i: src/core/hub.c.i

.PHONY : src/core/hub.i

# target to preprocess a source file
src/core/hub.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/hub.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/hub.c.i
.PHONY : src/core/hub.c.i

src/core/hub.s: src/core/hub.c.s

.PHONY : src/core/hub.s

# target to generate assembly for a file
src/core/hub.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/hub.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/hub.c.s
.PHONY : src/core/hub.c.s

src/core/hubevent.o: src/core/hubevent.c.o

.PHONY : src/core/hubevent.o

# target to build an object file
src/core/hubevent.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/hubevent.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/hubevent.c.o
.PHONY : src/core/hubevent.c.o

src/core/hubevent.i: src/core/hubevent.c.i

.PHONY : src/core/hubevent.i

# target to preprocess a source file
src/core/hubevent.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/hubevent.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/hubevent.c.i
.PHONY : src/core/hubevent.c.i

src/core/hubevent.s: src/core/hubevent.c.s

.PHONY : src/core/hubevent.s

# target to generate assembly for a file
src/core/hubevent.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/hubevent.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/hubevent.c.s
.PHONY : src/core/hubevent.c.s

src/core/inf.o: src/core/inf.c.o

.PHONY : src/core/inf.o

# target to build an object file
src/core/inf.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/inf.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/inf.c.o
.PHONY : src/core/inf.c.o

src/core/inf.i: src/core/inf.c.i

.PHONY : src/core/inf.i

# target to preprocess a source file
src/core/inf.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/inf.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/inf.c.i
.PHONY : src/core/inf.c.i

src/core/inf.s: src/core/inf.c.s

.PHONY : src/core/inf.s

# target to generate assembly for a file
src/core/inf.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/inf.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/inf.c.s
.PHONY : src/core/inf.c.s

src/core/ioqueue.o: src/core/ioqueue.c.o

.PHONY : src/core/ioqueue.o

# target to build an object file
src/core/ioqueue.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/ioqueue.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/ioqueue.c.o
	$(MAKE) -f CMakeFiles/adcclient.dir/build.make CMakeFiles/adcclient.dir/src/core/ioqueue.c.o
.PHONY : src/core/ioqueue.c.o

src/core/ioqueue.i: src/core/ioqueue.c.i

.PHONY : src/core/ioqueue.i

# target to preprocess a source file
src/core/ioqueue.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/ioqueue.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/ioqueue.c.i
	$(MAKE) -f CMakeFiles/adcclient.dir/build.make CMakeFiles/adcclient.dir/src/core/ioqueue.c.i
.PHONY : src/core/ioqueue.c.i

src/core/ioqueue.s: src/core/ioqueue.c.s

.PHONY : src/core/ioqueue.s

# target to generate assembly for a file
src/core/ioqueue.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/ioqueue.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/ioqueue.c.s
	$(MAKE) -f CMakeFiles/adcclient.dir/build.make CMakeFiles/adcclient.dir/src/core/ioqueue.c.s
.PHONY : src/core/ioqueue.c.s

src/core/main.o: src/core/main.c.o

.PHONY : src/core/main.o

# target to build an object file
src/core/main.c.o:
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/main.c.o
.PHONY : src/core/main.c.o

src/core/main.i: src/core/main.c.i

.PHONY : src/core/main.i

# target to preprocess a source file
src/core/main.c.i:
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/main.c.i
.PHONY : src/core/main.c.i

src/core/main.s: src/core/main.c.s

.PHONY : src/core/main.s

# target to generate assembly for a file
src/core/main.c.s:
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/main.c.s
.PHONY : src/core/main.c.s

src/core/netevent.o: src/core/netevent.c.o

.PHONY : src/core/netevent.o

# target to build an object file
src/core/netevent.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/netevent.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/netevent.c.o
.PHONY : src/core/netevent.c.o

src/core/netevent.i: src/core/netevent.c.i

.PHONY : src/core/netevent.i

# target to preprocess a source file
src/core/netevent.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/netevent.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/netevent.c.i
.PHONY : src/core/netevent.c.i

src/core/netevent.s: src/core/netevent.c.s

.PHONY : src/core/netevent.s

# target to generate assembly for a file
src/core/netevent.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/netevent.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/netevent.c.s
.PHONY : src/core/netevent.c.s

src/core/plugincallback.o: src/core/plugincallback.c.o

.PHONY : src/core/plugincallback.o

# target to build an object file
src/core/plugincallback.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/plugincallback.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/plugincallback.c.o
.PHONY : src/core/plugincallback.c.o

src/core/plugincallback.i: src/core/plugincallback.c.i

.PHONY : src/core/plugincallback.i

# target to preprocess a source file
src/core/plugincallback.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/plugincallback.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/plugincallback.c.i
.PHONY : src/core/plugincallback.c.i

src/core/plugincallback.s: src/core/plugincallback.c.s

.PHONY : src/core/plugincallback.s

# target to generate assembly for a file
src/core/plugincallback.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/plugincallback.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/plugincallback.c.s
.PHONY : src/core/plugincallback.c.s

src/core/plugininvoke.o: src/core/plugininvoke.c.o

.PHONY : src/core/plugininvoke.o

# target to build an object file
src/core/plugininvoke.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/plugininvoke.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/plugininvoke.c.o
.PHONY : src/core/plugininvoke.c.o

src/core/plugininvoke.i: src/core/plugininvoke.c.i

.PHONY : src/core/plugininvoke.i

# target to preprocess a source file
src/core/plugininvoke.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/plugininvoke.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/plugininvoke.c.i
.PHONY : src/core/plugininvoke.c.i

src/core/plugininvoke.s: src/core/plugininvoke.c.s

.PHONY : src/core/plugininvoke.s

# target to generate assembly for a file
src/core/plugininvoke.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/plugininvoke.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/plugininvoke.c.s
.PHONY : src/core/plugininvoke.c.s

src/core/pluginloader.o: src/core/pluginloader.c.o

.PHONY : src/core/pluginloader.o

# target to build an object file
src/core/pluginloader.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/pluginloader.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/pluginloader.c.o
.PHONY : src/core/pluginloader.c.o

src/core/pluginloader.i: src/core/pluginloader.c.i

.PHONY : src/core/pluginloader.i

# target to preprocess a source file
src/core/pluginloader.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/pluginloader.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/pluginloader.c.i
.PHONY : src/core/pluginloader.c.i

src/core/pluginloader.s: src/core/pluginloader.c.s

.PHONY : src/core/pluginloader.s

# target to generate assembly for a file
src/core/pluginloader.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/pluginloader.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/pluginloader.c.s
.PHONY : src/core/pluginloader.c.s

src/core/probe.o: src/core/probe.c.o

.PHONY : src/core/probe.o

# target to build an object file
src/core/probe.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/probe.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/probe.c.o
.PHONY : src/core/probe.c.o

src/core/probe.i: src/core/probe.c.i

.PHONY : src/core/probe.i

# target to preprocess a source file
src/core/probe.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/probe.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/probe.c.i
.PHONY : src/core/probe.c.i

src/core/probe.s: src/core/probe.c.s

.PHONY : src/core/probe.s

# target to generate assembly for a file
src/core/probe.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/probe.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/probe.c.s
.PHONY : src/core/probe.c.s

src/core/route.o: src/core/route.c.o

.PHONY : src/core/route.o

# target to build an object file
src/core/route.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/route.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/route.c.o
.PHONY : src/core/route.c.o

src/core/route.i: src/core/route.c.i

.PHONY : src/core/route.i

# target to preprocess a source file
src/core/route.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/route.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/route.c.i
.PHONY : src/core/route.c.i

src/core/route.s: src/core/route.c.s

.PHONY : src/core/route.s

# target to generate assembly for a file
src/core/route.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/route.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/route.c.s
.PHONY : src/core/route.c.s

src/core/user.o: src/core/user.c.o

.PHONY : src/core/user.o

# target to build an object file
src/core/user.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/user.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/user.c.o
.PHONY : src/core/user.c.o

src/core/user.i: src/core/user.c.i

.PHONY : src/core/user.i

# target to preprocess a source file
src/core/user.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/user.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/user.c.i
.PHONY : src/core/user.c.i

src/core/user.s: src/core/user.c.s

.PHONY : src/core/user.s

# target to generate assembly for a file
src/core/user.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/user.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/user.c.s
.PHONY : src/core/user.c.s

src/core/usermanager.o: src/core/usermanager.c.o

.PHONY : src/core/usermanager.o

# target to build an object file
src/core/usermanager.c.o:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/usermanager.c.o
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/usermanager.c.o
.PHONY : src/core/usermanager.c.o

src/core/usermanager.i: src/core/usermanager.c.i

.PHONY : src/core/usermanager.i

# target to preprocess a source file
src/core/usermanager.c.i:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/usermanager.c.i
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/usermanager.c.i
.PHONY : src/core/usermanager.c.i

src/core/usermanager.s: src/core/usermanager.c.s

.PHONY : src/core/usermanager.s

# target to generate assembly for a file
src/core/usermanager.c.s:
	$(MAKE) -f CMakeFiles/autotest-bin.dir/build.make CMakeFiles/autotest-bin.dir/src/core/usermanager.c.s
	$(MAKE) -f CMakeFiles/uhub.dir/build.make CMakeFiles/uhub.dir/src/core/usermanager.c.s
.PHONY : src/core/usermanager.c.s

src/network/backend.o: src/network/backend.c.o

.PHONY : src/network/backend.o

# target to build an object file
src/network/backend.c.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/backend.c.o
.PHONY : src/network/backend.c.o

src/network/backend.i: src/network/backend.c.i

.PHONY : src/network/backend.i

# target to preprocess a source file
src/network/backend.c.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/backend.c.i
.PHONY : src/network/backend.c.i

src/network/backend.s: src/network/backend.c.s

.PHONY : src/network/backend.s

# target to generate assembly for a file
src/network/backend.c.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/backend.c.s
.PHONY : src/network/backend.c.s

src/network/connection.o: src/network/connection.c.o

.PHONY : src/network/connection.o

# target to build an object file
src/network/connection.c.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/connection.c.o
.PHONY : src/network/connection.c.o

src/network/connection.i: src/network/connection.c.i

.PHONY : src/network/connection.i

# target to preprocess a source file
src/network/connection.c.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/connection.c.i
.PHONY : src/network/connection.c.i

src/network/connection.s: src/network/connection.c.s

.PHONY : src/network/connection.s

# target to generate assembly for a file
src/network/connection.c.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/connection.c.s
.PHONY : src/network/connection.c.s

src/network/dnsresolver.o: src/network/dnsresolver.c.o

.PHONY : src/network/dnsresolver.o

# target to build an object file
src/network/dnsresolver.c.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/dnsresolver.c.o
.PHONY : src/network/dnsresolver.c.o

src/network/dnsresolver.i: src/network/dnsresolver.c.i

.PHONY : src/network/dnsresolver.i

# target to preprocess a source file
src/network/dnsresolver.c.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/dnsresolver.c.i
.PHONY : src/network/dnsresolver.c.i

src/network/dnsresolver.s: src/network/dnsresolver.c.s

.PHONY : src/network/dnsresolver.s

# target to generate assembly for a file
src/network/dnsresolver.c.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/dnsresolver.c.s
.PHONY : src/network/dnsresolver.c.s

src/network/epoll.o: src/network/epoll.c.o

.PHONY : src/network/epoll.o

# target to build an object file
src/network/epoll.c.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/epoll.c.o
.PHONY : src/network/epoll.c.o

src/network/epoll.i: src/network/epoll.c.i

.PHONY : src/network/epoll.i

# target to preprocess a source file
src/network/epoll.c.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/epoll.c.i
.PHONY : src/network/epoll.c.i

src/network/epoll.s: src/network/epoll.c.s

.PHONY : src/network/epoll.s

# target to generate assembly for a file
src/network/epoll.c.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/epoll.c.s
.PHONY : src/network/epoll.c.s

src/network/ipcalc.o: src/network/ipcalc.c.o

.PHONY : src/network/ipcalc.o

# target to build an object file
src/network/ipcalc.c.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/ipcalc.c.o
.PHONY : src/network/ipcalc.c.o

src/network/ipcalc.i: src/network/ipcalc.c.i

.PHONY : src/network/ipcalc.i

# target to preprocess a source file
src/network/ipcalc.c.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/ipcalc.c.i
.PHONY : src/network/ipcalc.c.i

src/network/ipcalc.s: src/network/ipcalc.c.s

.PHONY : src/network/ipcalc.s

# target to generate assembly for a file
src/network/ipcalc.c.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/ipcalc.c.s
.PHONY : src/network/ipcalc.c.s

src/network/kqueue.o: src/network/kqueue.c.o

.PHONY : src/network/kqueue.o

# target to build an object file
src/network/kqueue.c.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/kqueue.c.o
.PHONY : src/network/kqueue.c.o

src/network/kqueue.i: src/network/kqueue.c.i

.PHONY : src/network/kqueue.i

# target to preprocess a source file
src/network/kqueue.c.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/kqueue.c.i
.PHONY : src/network/kqueue.c.i

src/network/kqueue.s: src/network/kqueue.c.s

.PHONY : src/network/kqueue.s

# target to generate assembly for a file
src/network/kqueue.c.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/kqueue.c.s
.PHONY : src/network/kqueue.c.s

src/network/network.o: src/network/network.c.o

.PHONY : src/network/network.o

# target to build an object file
src/network/network.c.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/network.c.o
.PHONY : src/network/network.c.o

src/network/network.i: src/network/network.c.i

.PHONY : src/network/network.i

# target to preprocess a source file
src/network/network.c.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/network.c.i
.PHONY : src/network/network.c.i

src/network/network.s: src/network/network.c.s

.PHONY : src/network/network.s

# target to generate assembly for a file
src/network/network.c.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/network.c.s
.PHONY : src/network/network.c.s

src/network/notify.o: src/network/notify.c.o

.PHONY : src/network/notify.o

# target to build an object file
src/network/notify.c.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/notify.c.o
.PHONY : src/network/notify.c.o

src/network/notify.i: src/network/notify.c.i

.PHONY : src/network/notify.i

# target to preprocess a source file
src/network/notify.c.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/notify.c.i
.PHONY : src/network/notify.c.i

src/network/notify.s: src/network/notify.c.s

.PHONY : src/network/notify.s

# target to generate assembly for a file
src/network/notify.c.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/notify.c.s
.PHONY : src/network/notify.c.s

src/network/openssl.o: src/network/openssl.c.o

.PHONY : src/network/openssl.o

# target to build an object file
src/network/openssl.c.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/openssl.c.o
.PHONY : src/network/openssl.c.o

src/network/openssl.i: src/network/openssl.c.i

.PHONY : src/network/openssl.i

# target to preprocess a source file
src/network/openssl.c.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/openssl.c.i
.PHONY : src/network/openssl.c.i

src/network/openssl.s: src/network/openssl.c.s

.PHONY : src/network/openssl.s

# target to generate assembly for a file
src/network/openssl.c.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/openssl.c.s
.PHONY : src/network/openssl.c.s

src/network/select.o: src/network/select.c.o

.PHONY : src/network/select.o

# target to build an object file
src/network/select.c.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/select.c.o
.PHONY : src/network/select.c.o

src/network/select.i: src/network/select.c.i

.PHONY : src/network/select.i

# target to preprocess a source file
src/network/select.c.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/select.c.i
.PHONY : src/network/select.c.i

src/network/select.s: src/network/select.c.s

.PHONY : src/network/select.s

# target to generate assembly for a file
src/network/select.c.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/select.c.s
.PHONY : src/network/select.c.s

src/network/timeout.o: src/network/timeout.c.o

.PHONY : src/network/timeout.o

# target to build an object file
src/network/timeout.c.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/timeout.c.o
.PHONY : src/network/timeout.c.o

src/network/timeout.i: src/network/timeout.c.i

.PHONY : src/network/timeout.i

# target to preprocess a source file
src/network/timeout.c.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/timeout.c.i
.PHONY : src/network/timeout.c.i

src/network/timeout.s: src/network/timeout.c.s

.PHONY : src/network/timeout.s

# target to generate assembly for a file
src/network/timeout.c.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/timeout.c.s
.PHONY : src/network/timeout.c.s

src/network/timer.o: src/network/timer.c.o

.PHONY : src/network/timer.o

# target to build an object file
src/network/timer.c.o:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/timer.c.o
.PHONY : src/network/timer.c.o

src/network/timer.i: src/network/timer.c.i

.PHONY : src/network/timer.i

# target to preprocess a source file
src/network/timer.c.i:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/timer.c.i
.PHONY : src/network/timer.c.i

src/network/timer.s: src/network/timer.c.s

.PHONY : src/network/timer.s

# target to generate assembly for a file
src/network/timer.c.s:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/src/network/timer.c.s
.PHONY : src/network/timer.c.s

src/plugins/mod_auth_simple.o: src/plugins/mod_auth_simple.c.o

.PHONY : src/plugins/mod_auth_simple.o

# target to build an object file
src/plugins/mod_auth_simple.c.o:
	$(MAKE) -f CMakeFiles/mod_auth_simple.dir/build.make CMakeFiles/mod_auth_simple.dir/src/plugins/mod_auth_simple.c.o
.PHONY : src/plugins/mod_auth_simple.c.o

src/plugins/mod_auth_simple.i: src/plugins/mod_auth_simple.c.i

.PHONY : src/plugins/mod_auth_simple.i

# target to preprocess a source file
src/plugins/mod_auth_simple.c.i:
	$(MAKE) -f CMakeFiles/mod_auth_simple.dir/build.make CMakeFiles/mod_auth_simple.dir/src/plugins/mod_auth_simple.c.i
.PHONY : src/plugins/mod_auth_simple.c.i

src/plugins/mod_auth_simple.s: src/plugins/mod_auth_simple.c.s

.PHONY : src/plugins/mod_auth_simple.s

# target to generate assembly for a file
src/plugins/mod_auth_simple.c.s:
	$(MAKE) -f CMakeFiles/mod_auth_simple.dir/build.make CMakeFiles/mod_auth_simple.dir/src/plugins/mod_auth_simple.c.s
.PHONY : src/plugins/mod_auth_simple.c.s

src/plugins/mod_auth_sqlite.o: src/plugins/mod_auth_sqlite.c.o

.PHONY : src/plugins/mod_auth_sqlite.o

# target to build an object file
src/plugins/mod_auth_sqlite.c.o:
	$(MAKE) -f CMakeFiles/mod_auth_sqlite.dir/build.make CMakeFiles/mod_auth_sqlite.dir/src/plugins/mod_auth_sqlite.c.o
.PHONY : src/plugins/mod_auth_sqlite.c.o

src/plugins/mod_auth_sqlite.i: src/plugins/mod_auth_sqlite.c.i

.PHONY : src/plugins/mod_auth_sqlite.i

# target to preprocess a source file
src/plugins/mod_auth_sqlite.c.i:
	$(MAKE) -f CMakeFiles/mod_auth_sqlite.dir/build.make CMakeFiles/mod_auth_sqlite.dir/src/plugins/mod_auth_sqlite.c.i
.PHONY : src/plugins/mod_auth_sqlite.c.i

src/plugins/mod_auth_sqlite.s: src/plugins/mod_auth_sqlite.c.s

.PHONY : src/plugins/mod_auth_sqlite.s

# target to generate assembly for a file
src/plugins/mod_auth_sqlite.c.s:
	$(MAKE) -f CMakeFiles/mod_auth_sqlite.dir/build.make CMakeFiles/mod_auth_sqlite.dir/src/plugins/mod_auth_sqlite.c.s
.PHONY : src/plugins/mod_auth_sqlite.c.s

src/plugins/mod_chat_history.o: src/plugins/mod_chat_history.c.o

.PHONY : src/plugins/mod_chat_history.o

# target to build an object file
src/plugins/mod_chat_history.c.o:
	$(MAKE) -f CMakeFiles/mod_chat_history.dir/build.make CMakeFiles/mod_chat_history.dir/src/plugins/mod_chat_history.c.o
.PHONY : src/plugins/mod_chat_history.c.o

src/plugins/mod_chat_history.i: src/plugins/mod_chat_history.c.i

.PHONY : src/plugins/mod_chat_history.i

# target to preprocess a source file
src/plugins/mod_chat_history.c.i:
	$(MAKE) -f CMakeFiles/mod_chat_history.dir/build.make CMakeFiles/mod_chat_history.dir/src/plugins/mod_chat_history.c.i
.PHONY : src/plugins/mod_chat_history.c.i

src/plugins/mod_chat_history.s: src/plugins/mod_chat_history.c.s

.PHONY : src/plugins/mod_chat_history.s

# target to generate assembly for a file
src/plugins/mod_chat_history.c.s:
	$(MAKE) -f CMakeFiles/mod_chat_history.dir/build.make CMakeFiles/mod_chat_history.dir/src/plugins/mod_chat_history.c.s
.PHONY : src/plugins/mod_chat_history.c.s

src/plugins/mod_chat_history_sqlite.o: src/plugins/mod_chat_history_sqlite.c.o

.PHONY : src/plugins/mod_chat_history_sqlite.o

# target to build an object file
src/plugins/mod_chat_history_sqlite.c.o:
	$(MAKE) -f CMakeFiles/mod_chat_history_sqlite.dir/build.make CMakeFiles/mod_chat_history_sqlite.dir/src/plugins/mod_chat_history_sqlite.c.o
.PHONY : src/plugins/mod_chat_history_sqlite.c.o

src/plugins/mod_chat_history_sqlite.i: src/plugins/mod_chat_history_sqlite.c.i

.PHONY : src/plugins/mod_chat_history_sqlite.i

# target to preprocess a source file
src/plugins/mod_chat_history_sqlite.c.i:
	$(MAKE) -f CMakeFiles/mod_chat_history_sqlite.dir/build.make CMakeFiles/mod_chat_history_sqlite.dir/src/plugins/mod_chat_history_sqlite.c.i
.PHONY : src/plugins/mod_chat_history_sqlite.c.i

src/plugins/mod_chat_history_sqlite.s: src/plugins/mod_chat_history_sqlite.c.s

.PHONY : src/plugins/mod_chat_history_sqlite.s

# target to generate assembly for a file
src/plugins/mod_chat_history_sqlite.c.s:
	$(MAKE) -f CMakeFiles/mod_chat_history_sqlite.dir/build.make CMakeFiles/mod_chat_history_sqlite.dir/src/plugins/mod_chat_history_sqlite.c.s
.PHONY : src/plugins/mod_chat_history_sqlite.c.s

src/plugins/mod_chat_only.o: src/plugins/mod_chat_only.c.o

.PHONY : src/plugins/mod_chat_only.o

# target to build an object file
src/plugins/mod_chat_only.c.o:
	$(MAKE) -f CMakeFiles/mod_chat_only.dir/build.make CMakeFiles/mod_chat_only.dir/src/plugins/mod_chat_only.c.o
.PHONY : src/plugins/mod_chat_only.c.o

src/plugins/mod_chat_only.i: src/plugins/mod_chat_only.c.i

.PHONY : src/plugins/mod_chat_only.i

# target to preprocess a source file
src/plugins/mod_chat_only.c.i:
	$(MAKE) -f CMakeFiles/mod_chat_only.dir/build.make CMakeFiles/mod_chat_only.dir/src/plugins/mod_chat_only.c.i
.PHONY : src/plugins/mod_chat_only.c.i

src/plugins/mod_chat_only.s: src/plugins/mod_chat_only.c.s

.PHONY : src/plugins/mod_chat_only.s

# target to generate assembly for a file
src/plugins/mod_chat_only.c.s:
	$(MAKE) -f CMakeFiles/mod_chat_only.dir/build.make CMakeFiles/mod_chat_only.dir/src/plugins/mod_chat_only.c.s
.PHONY : src/plugins/mod_chat_only.c.s

src/plugins/mod_example.o: src/plugins/mod_example.c.o

.PHONY : src/plugins/mod_example.o

# target to build an object file
src/plugins/mod_example.c.o:
	$(MAKE) -f CMakeFiles/mod_example.dir/build.make CMakeFiles/mod_example.dir/src/plugins/mod_example.c.o
.PHONY : src/plugins/mod_example.c.o

src/plugins/mod_example.i: src/plugins/mod_example.c.i

.PHONY : src/plugins/mod_example.i

# target to preprocess a source file
src/plugins/mod_example.c.i:
	$(MAKE) -f CMakeFiles/mod_example.dir/build.make CMakeFiles/mod_example.dir/src/plugins/mod_example.c.i
.PHONY : src/plugins/mod_example.c.i

src/plugins/mod_example.s: src/plugins/mod_example.c.s

.PHONY : src/plugins/mod_example.s

# target to generate assembly for a file
src/plugins/mod_example.c.s:
	$(MAKE) -f CMakeFiles/mod_example.dir/build.make CMakeFiles/mod_example.dir/src/plugins/mod_example.c.s
.PHONY : src/plugins/mod_example.c.s

src/plugins/mod_logging.o: src/plugins/mod_logging.c.o

.PHONY : src/plugins/mod_logging.o

# target to build an object file
src/plugins/mod_logging.c.o:
	$(MAKE) -f CMakeFiles/mod_logging.dir/build.make CMakeFiles/mod_logging.dir/src/plugins/mod_logging.c.o
.PHONY : src/plugins/mod_logging.c.o

src/plugins/mod_logging.i: src/plugins/mod_logging.c.i

.PHONY : src/plugins/mod_logging.i

# target to preprocess a source file
src/plugins/mod_logging.c.i:
	$(MAKE) -f CMakeFiles/mod_logging.dir/build.make CMakeFiles/mod_logging.dir/src/plugins/mod_logging.c.i
.PHONY : src/plugins/mod_logging.c.i

src/plugins/mod_logging.s: src/plugins/mod_logging.c.s

.PHONY : src/plugins/mod_logging.s

# target to generate assembly for a file
src/plugins/mod_logging.c.s:
	$(MAKE) -f CMakeFiles/mod_logging.dir/build.make CMakeFiles/mod_logging.dir/src/plugins/mod_logging.c.s
.PHONY : src/plugins/mod_logging.c.s

src/plugins/mod_no_guest_downloads.o: src/plugins/mod_no_guest_downloads.c.o

.PHONY : src/plugins/mod_no_guest_downloads.o

# target to build an object file
src/plugins/mod_no_guest_downloads.c.o:
	$(MAKE) -f CMakeFiles/mod_no_guest_downloads.dir/build.make CMakeFiles/mod_no_guest_downloads.dir/src/plugins/mod_no_guest_downloads.c.o
.PHONY : src/plugins/mod_no_guest_downloads.c.o

src/plugins/mod_no_guest_downloads.i: src/plugins/mod_no_guest_downloads.c.i

.PHONY : src/plugins/mod_no_guest_downloads.i

# target to preprocess a source file
src/plugins/mod_no_guest_downloads.c.i:
	$(MAKE) -f CMakeFiles/mod_no_guest_downloads.dir/build.make CMakeFiles/mod_no_guest_downloads.dir/src/plugins/mod_no_guest_downloads.c.i
.PHONY : src/plugins/mod_no_guest_downloads.c.i

src/plugins/mod_no_guest_downloads.s: src/plugins/mod_no_guest_downloads.c.s

.PHONY : src/plugins/mod_no_guest_downloads.s

# target to generate assembly for a file
src/plugins/mod_no_guest_downloads.c.s:
	$(MAKE) -f CMakeFiles/mod_no_guest_downloads.dir/build.make CMakeFiles/mod_no_guest_downloads.dir/src/plugins/mod_no_guest_downloads.c.s
.PHONY : src/plugins/mod_no_guest_downloads.c.s

src/plugins/mod_topic.o: src/plugins/mod_topic.c.o

.PHONY : src/plugins/mod_topic.o

# target to build an object file
src/plugins/mod_topic.c.o:
	$(MAKE) -f CMakeFiles/mod_topic.dir/build.make CMakeFiles/mod_topic.dir/src/plugins/mod_topic.c.o
.PHONY : src/plugins/mod_topic.c.o

src/plugins/mod_topic.i: src/plugins/mod_topic.c.i

.PHONY : src/plugins/mod_topic.i

# target to preprocess a source file
src/plugins/mod_topic.c.i:
	$(MAKE) -f CMakeFiles/mod_topic.dir/build.make CMakeFiles/mod_topic.dir/src/plugins/mod_topic.c.i
.PHONY : src/plugins/mod_topic.c.i

src/plugins/mod_topic.s: src/plugins/mod_topic.c.s

.PHONY : src/plugins/mod_topic.s

# target to generate assembly for a file
src/plugins/mod_topic.c.s:
	$(MAKE) -f CMakeFiles/mod_topic.dir/build.make CMakeFiles/mod_topic.dir/src/plugins/mod_topic.c.s
.PHONY : src/plugins/mod_topic.c.s

src/plugins/mod_welcome.o: src/plugins/mod_welcome.c.o

.PHONY : src/plugins/mod_welcome.o

# target to build an object file
src/plugins/mod_welcome.c.o:
	$(MAKE) -f CMakeFiles/mod_welcome.dir/build.make CMakeFiles/mod_welcome.dir/src/plugins/mod_welcome.c.o
.PHONY : src/plugins/mod_welcome.c.o

src/plugins/mod_welcome.i: src/plugins/mod_welcome.c.i

.PHONY : src/plugins/mod_welcome.i

# target to preprocess a source file
src/plugins/mod_welcome.c.i:
	$(MAKE) -f CMakeFiles/mod_welcome.dir/build.make CMakeFiles/mod_welcome.dir/src/plugins/mod_welcome.c.i
.PHONY : src/plugins/mod_welcome.c.i

src/plugins/mod_welcome.s: src/plugins/mod_welcome.c.s

.PHONY : src/plugins/mod_welcome.s

# target to generate assembly for a file
src/plugins/mod_welcome.c.s:
	$(MAKE) -f CMakeFiles/mod_welcome.dir/build.make CMakeFiles/mod_welcome.dir/src/plugins/mod_welcome.c.s
.PHONY : src/plugins/mod_welcome.c.s

src/tools/adcclient.o: src/tools/adcclient.c.o

.PHONY : src/tools/adcclient.o

# target to build an object file
src/tools/adcclient.c.o:
	$(MAKE) -f CMakeFiles/adcclient.dir/build.make CMakeFiles/adcclient.dir/src/tools/adcclient.c.o
.PHONY : src/tools/adcclient.c.o

src/tools/adcclient.i: src/tools/adcclient.c.i

.PHONY : src/tools/adcclient.i

# target to preprocess a source file
src/tools/adcclient.c.i:
	$(MAKE) -f CMakeFiles/adcclient.dir/build.make CMakeFiles/adcclient.dir/src/tools/adcclient.c.i
.PHONY : src/tools/adcclient.c.i

src/tools/adcclient.s: src/tools/adcclient.c.s

.PHONY : src/tools/adcclient.s

# target to generate assembly for a file
src/tools/adcclient.c.s:
	$(MAKE) -f CMakeFiles/adcclient.dir/build.make CMakeFiles/adcclient.dir/src/tools/adcclient.c.s
.PHONY : src/tools/adcclient.c.s

src/tools/admin.o: src/tools/admin.c.o

.PHONY : src/tools/admin.o

# target to build an object file
src/tools/admin.c.o:
	$(MAKE) -f CMakeFiles/uhub-admin.dir/build.make CMakeFiles/uhub-admin.dir/src/tools/admin.c.o
.PHONY : src/tools/admin.c.o

src/tools/admin.i: src/tools/admin.c.i

.PHONY : src/tools/admin.i

# target to preprocess a source file
src/tools/admin.c.i:
	$(MAKE) -f CMakeFiles/uhub-admin.dir/build.make CMakeFiles/uhub-admin.dir/src/tools/admin.c.i
.PHONY : src/tools/admin.c.i

src/tools/admin.s: src/tools/admin.c.s

.PHONY : src/tools/admin.s

# target to generate assembly for a file
src/tools/admin.c.s:
	$(MAKE) -f CMakeFiles/uhub-admin.dir/build.make CMakeFiles/uhub-admin.dir/src/tools/admin.c.s
.PHONY : src/tools/admin.c.s

src/tools/uhub-passwd.o: src/tools/uhub-passwd.c.o

.PHONY : src/tools/uhub-passwd.o

# target to build an object file
src/tools/uhub-passwd.c.o:
	$(MAKE) -f CMakeFiles/uhub-passwd.dir/build.make CMakeFiles/uhub-passwd.dir/src/tools/uhub-passwd.c.o
.PHONY : src/tools/uhub-passwd.c.o

src/tools/uhub-passwd.i: src/tools/uhub-passwd.c.i

.PHONY : src/tools/uhub-passwd.i

# target to preprocess a source file
src/tools/uhub-passwd.c.i:
	$(MAKE) -f CMakeFiles/uhub-passwd.dir/build.make CMakeFiles/uhub-passwd.dir/src/tools/uhub-passwd.c.i
.PHONY : src/tools/uhub-passwd.c.i

src/tools/uhub-passwd.s: src/tools/uhub-passwd.c.s

.PHONY : src/tools/uhub-passwd.s

# target to generate assembly for a file
src/tools/uhub-passwd.c.s:
	$(MAKE) -f CMakeFiles/uhub-passwd.dir/build.make CMakeFiles/uhub-passwd.dir/src/tools/uhub-passwd.c.s
.PHONY : src/tools/uhub-passwd.c.s

src/util/cbuffer.o: src/util/cbuffer.c.o

.PHONY : src/util/cbuffer.o

# target to build an object file
src/util/cbuffer.c.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/cbuffer.c.o
.PHONY : src/util/cbuffer.c.o

src/util/cbuffer.i: src/util/cbuffer.c.i

.PHONY : src/util/cbuffer.i

# target to preprocess a source file
src/util/cbuffer.c.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/cbuffer.c.i
.PHONY : src/util/cbuffer.c.i

src/util/cbuffer.s: src/util/cbuffer.c.s

.PHONY : src/util/cbuffer.s

# target to generate assembly for a file
src/util/cbuffer.c.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/cbuffer.c.s
.PHONY : src/util/cbuffer.c.s

src/util/config_token.o: src/util/config_token.c.o

.PHONY : src/util/config_token.o

# target to build an object file
src/util/config_token.c.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/config_token.c.o
.PHONY : src/util/config_token.c.o

src/util/config_token.i: src/util/config_token.c.i

.PHONY : src/util/config_token.i

# target to preprocess a source file
src/util/config_token.c.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/config_token.c.i
.PHONY : src/util/config_token.c.i

src/util/config_token.s: src/util/config_token.c.s

.PHONY : src/util/config_token.s

# target to generate assembly for a file
src/util/config_token.c.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/config_token.c.s
.PHONY : src/util/config_token.c.s

src/util/credentials.o: src/util/credentials.c.o

.PHONY : src/util/credentials.o

# target to build an object file
src/util/credentials.c.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/credentials.c.o
.PHONY : src/util/credentials.c.o

src/util/credentials.i: src/util/credentials.c.i

.PHONY : src/util/credentials.i

# target to preprocess a source file
src/util/credentials.c.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/credentials.c.i
.PHONY : src/util/credentials.c.i

src/util/credentials.s: src/util/credentials.c.s

.PHONY : src/util/credentials.s

# target to generate assembly for a file
src/util/credentials.c.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/credentials.c.s
.PHONY : src/util/credentials.c.s

src/util/floodctl.o: src/util/floodctl.c.o

.PHONY : src/util/floodctl.o

# target to build an object file
src/util/floodctl.c.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/floodctl.c.o
.PHONY : src/util/floodctl.c.o

src/util/floodctl.i: src/util/floodctl.c.i

.PHONY : src/util/floodctl.i

# target to preprocess a source file
src/util/floodctl.c.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/floodctl.c.i
.PHONY : src/util/floodctl.c.i

src/util/floodctl.s: src/util/floodctl.c.s

.PHONY : src/util/floodctl.s

# target to generate assembly for a file
src/util/floodctl.c.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/floodctl.c.s
.PHONY : src/util/floodctl.c.s

src/util/getopt.o: src/util/getopt.c.o

.PHONY : src/util/getopt.o

# target to build an object file
src/util/getopt.c.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/getopt.c.o
.PHONY : src/util/getopt.c.o

src/util/getopt.i: src/util/getopt.c.i

.PHONY : src/util/getopt.i

# target to preprocess a source file
src/util/getopt.c.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/getopt.c.i
.PHONY : src/util/getopt.c.i

src/util/getopt.s: src/util/getopt.c.s

.PHONY : src/util/getopt.s

# target to generate assembly for a file
src/util/getopt.c.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/getopt.c.s
.PHONY : src/util/getopt.c.s

src/util/list.o: src/util/list.c.o

.PHONY : src/util/list.o

# target to build an object file
src/util/list.c.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/list.c.o
.PHONY : src/util/list.c.o

src/util/list.i: src/util/list.c.i

.PHONY : src/util/list.i

# target to preprocess a source file
src/util/list.c.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/list.c.i
.PHONY : src/util/list.c.i

src/util/list.s: src/util/list.c.s

.PHONY : src/util/list.s

# target to generate assembly for a file
src/util/list.c.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/list.c.s
.PHONY : src/util/list.c.s

src/util/log.o: src/util/log.c.o

.PHONY : src/util/log.o

# target to build an object file
src/util/log.c.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/log.c.o
.PHONY : src/util/log.c.o

src/util/log.i: src/util/log.c.i

.PHONY : src/util/log.i

# target to preprocess a source file
src/util/log.c.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/log.c.i
.PHONY : src/util/log.c.i

src/util/log.s: src/util/log.c.s

.PHONY : src/util/log.s

# target to generate assembly for a file
src/util/log.c.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/log.c.s
.PHONY : src/util/log.c.s

src/util/memory.o: src/util/memory.c.o

.PHONY : src/util/memory.o

# target to build an object file
src/util/memory.c.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/memory.c.o
.PHONY : src/util/memory.c.o

src/util/memory.i: src/util/memory.c.i

.PHONY : src/util/memory.i

# target to preprocess a source file
src/util/memory.c.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/memory.c.i
.PHONY : src/util/memory.c.i

src/util/memory.s: src/util/memory.c.s

.PHONY : src/util/memory.s

# target to generate assembly for a file
src/util/memory.c.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/memory.c.s
.PHONY : src/util/memory.c.s

src/util/misc.o: src/util/misc.c.o

.PHONY : src/util/misc.o

# target to build an object file
src/util/misc.c.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/misc.c.o
.PHONY : src/util/misc.c.o

src/util/misc.i: src/util/misc.c.i

.PHONY : src/util/misc.i

# target to preprocess a source file
src/util/misc.c.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/misc.c.i
.PHONY : src/util/misc.c.i

src/util/misc.s: src/util/misc.c.s

.PHONY : src/util/misc.s

# target to generate assembly for a file
src/util/misc.c.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/misc.c.s
.PHONY : src/util/misc.c.s

src/util/rbtree.o: src/util/rbtree.c.o

.PHONY : src/util/rbtree.o

# target to build an object file
src/util/rbtree.c.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/rbtree.c.o
.PHONY : src/util/rbtree.c.o

src/util/rbtree.i: src/util/rbtree.c.i

.PHONY : src/util/rbtree.i

# target to preprocess a source file
src/util/rbtree.c.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/rbtree.c.i
.PHONY : src/util/rbtree.c.i

src/util/rbtree.s: src/util/rbtree.c.s

.PHONY : src/util/rbtree.s

# target to generate assembly for a file
src/util/rbtree.c.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/rbtree.c.s
.PHONY : src/util/rbtree.c.s

src/util/threads.o: src/util/threads.c.o

.PHONY : src/util/threads.o

# target to build an object file
src/util/threads.c.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/threads.c.o
.PHONY : src/util/threads.c.o

src/util/threads.i: src/util/threads.c.i

.PHONY : src/util/threads.i

# target to preprocess a source file
src/util/threads.c.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/threads.c.i
.PHONY : src/util/threads.c.i

src/util/threads.s: src/util/threads.c.s

.PHONY : src/util/threads.s

# target to generate assembly for a file
src/util/threads.c.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/threads.c.s
.PHONY : src/util/threads.c.s

src/util/tiger.o: src/util/tiger.c.o

.PHONY : src/util/tiger.o

# target to build an object file
src/util/tiger.c.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/tiger.c.o
.PHONY : src/util/tiger.c.o

src/util/tiger.i: src/util/tiger.c.i

.PHONY : src/util/tiger.i

# target to preprocess a source file
src/util/tiger.c.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/tiger.c.i
.PHONY : src/util/tiger.c.i

src/util/tiger.s: src/util/tiger.c.s

.PHONY : src/util/tiger.s

# target to generate assembly for a file
src/util/tiger.c.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/util/tiger.c.s
.PHONY : src/util/tiger.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... mod_logging"
	@echo "... mod_welcome"
	@echo "... mod_example"
	@echo "... rebuild_cache"
	@echo "... mod_topic"
	@echo "... mod_auth_simple"
	@echo "... mod_auth_sqlite"
	@echo "... autotest-bin"
	@echo "... adc"
	@echo "... mod_chat_history"
	@echo "... uhub"
	@echo "... mod_chat_history_sqlite"
	@echo "... utils"
	@echo "... adcclient"
	@echo "... mod_chat_only"
	@echo "... network"
	@echo "... mod_no_guest_downloads"
	@echo "... uhub-admin"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... uhub-passwd"
	@echo "... edit_cache"
	@echo "... autotest/test.o"
	@echo "... autotest/test.i"
	@echo "... autotest/test.s"
	@echo "... src/adc/message.o"
	@echo "... src/adc/message.i"
	@echo "... src/adc/message.s"
	@echo "... src/adc/sid.o"
	@echo "... src/adc/sid.i"
	@echo "... src/adc/sid.s"
	@echo "... src/core/auth.o"
	@echo "... src/core/auth.i"
	@echo "... src/core/auth.s"
	@echo "... src/core/command_parser.o"
	@echo "... src/core/command_parser.i"
	@echo "... src/core/command_parser.s"
	@echo "... src/core/commands.o"
	@echo "... src/core/commands.i"
	@echo "... src/core/commands.s"
	@echo "... src/core/config.o"
	@echo "... src/core/config.i"
	@echo "... src/core/config.s"
	@echo "... src/core/eventqueue.o"
	@echo "... src/core/eventqueue.i"
	@echo "... src/core/eventqueue.s"
	@echo "... src/core/hub.o"
	@echo "... src/core/hub.i"
	@echo "... src/core/hub.s"
	@echo "... src/core/hubevent.o"
	@echo "... src/core/hubevent.i"
	@echo "... src/core/hubevent.s"
	@echo "... src/core/inf.o"
	@echo "... src/core/inf.i"
	@echo "... src/core/inf.s"
	@echo "... src/core/ioqueue.o"
	@echo "... src/core/ioqueue.i"
	@echo "... src/core/ioqueue.s"
	@echo "... src/core/main.o"
	@echo "... src/core/main.i"
	@echo "... src/core/main.s"
	@echo "... src/core/netevent.o"
	@echo "... src/core/netevent.i"
	@echo "... src/core/netevent.s"
	@echo "... src/core/plugincallback.o"
	@echo "... src/core/plugincallback.i"
	@echo "... src/core/plugincallback.s"
	@echo "... src/core/plugininvoke.o"
	@echo "... src/core/plugininvoke.i"
	@echo "... src/core/plugininvoke.s"
	@echo "... src/core/pluginloader.o"
	@echo "... src/core/pluginloader.i"
	@echo "... src/core/pluginloader.s"
	@echo "... src/core/probe.o"
	@echo "... src/core/probe.i"
	@echo "... src/core/probe.s"
	@echo "... src/core/route.o"
	@echo "... src/core/route.i"
	@echo "... src/core/route.s"
	@echo "... src/core/user.o"
	@echo "... src/core/user.i"
	@echo "... src/core/user.s"
	@echo "... src/core/usermanager.o"
	@echo "... src/core/usermanager.i"
	@echo "... src/core/usermanager.s"
	@echo "... src/network/backend.o"
	@echo "... src/network/backend.i"
	@echo "... src/network/backend.s"
	@echo "... src/network/connection.o"
	@echo "... src/network/connection.i"
	@echo "... src/network/connection.s"
	@echo "... src/network/dnsresolver.o"
	@echo "... src/network/dnsresolver.i"
	@echo "... src/network/dnsresolver.s"
	@echo "... src/network/epoll.o"
	@echo "... src/network/epoll.i"
	@echo "... src/network/epoll.s"
	@echo "... src/network/ipcalc.o"
	@echo "... src/network/ipcalc.i"
	@echo "... src/network/ipcalc.s"
	@echo "... src/network/kqueue.o"
	@echo "... src/network/kqueue.i"
	@echo "... src/network/kqueue.s"
	@echo "... src/network/network.o"
	@echo "... src/network/network.i"
	@echo "... src/network/network.s"
	@echo "... src/network/notify.o"
	@echo "... src/network/notify.i"
	@echo "... src/network/notify.s"
	@echo "... src/network/openssl.o"
	@echo "... src/network/openssl.i"
	@echo "... src/network/openssl.s"
	@echo "... src/network/select.o"
	@echo "... src/network/select.i"
	@echo "... src/network/select.s"
	@echo "... src/network/timeout.o"
	@echo "... src/network/timeout.i"
	@echo "... src/network/timeout.s"
	@echo "... src/network/timer.o"
	@echo "... src/network/timer.i"
	@echo "... src/network/timer.s"
	@echo "... src/plugins/mod_auth_simple.o"
	@echo "... src/plugins/mod_auth_simple.i"
	@echo "... src/plugins/mod_auth_simple.s"
	@echo "... src/plugins/mod_auth_sqlite.o"
	@echo "... src/plugins/mod_auth_sqlite.i"
	@echo "... src/plugins/mod_auth_sqlite.s"
	@echo "... src/plugins/mod_chat_history.o"
	@echo "... src/plugins/mod_chat_history.i"
	@echo "... src/plugins/mod_chat_history.s"
	@echo "... src/plugins/mod_chat_history_sqlite.o"
	@echo "... src/plugins/mod_chat_history_sqlite.i"
	@echo "... src/plugins/mod_chat_history_sqlite.s"
	@echo "... src/plugins/mod_chat_only.o"
	@echo "... src/plugins/mod_chat_only.i"
	@echo "... src/plugins/mod_chat_only.s"
	@echo "... src/plugins/mod_example.o"
	@echo "... src/plugins/mod_example.i"
	@echo "... src/plugins/mod_example.s"
	@echo "... src/plugins/mod_logging.o"
	@echo "... src/plugins/mod_logging.i"
	@echo "... src/plugins/mod_logging.s"
	@echo "... src/plugins/mod_no_guest_downloads.o"
	@echo "... src/plugins/mod_no_guest_downloads.i"
	@echo "... src/plugins/mod_no_guest_downloads.s"
	@echo "... src/plugins/mod_topic.o"
	@echo "... src/plugins/mod_topic.i"
	@echo "... src/plugins/mod_topic.s"
	@echo "... src/plugins/mod_welcome.o"
	@echo "... src/plugins/mod_welcome.i"
	@echo "... src/plugins/mod_welcome.s"
	@echo "... src/tools/adcclient.o"
	@echo "... src/tools/adcclient.i"
	@echo "... src/tools/adcclient.s"
	@echo "... src/tools/admin.o"
	@echo "... src/tools/admin.i"
	@echo "... src/tools/admin.s"
	@echo "... src/tools/uhub-passwd.o"
	@echo "... src/tools/uhub-passwd.i"
	@echo "... src/tools/uhub-passwd.s"
	@echo "... src/util/cbuffer.o"
	@echo "... src/util/cbuffer.i"
	@echo "... src/util/cbuffer.s"
	@echo "... src/util/config_token.o"
	@echo "... src/util/config_token.i"
	@echo "... src/util/config_token.s"
	@echo "... src/util/credentials.o"
	@echo "... src/util/credentials.i"
	@echo "... src/util/credentials.s"
	@echo "... src/util/floodctl.o"
	@echo "... src/util/floodctl.i"
	@echo "... src/util/floodctl.s"
	@echo "... src/util/getopt.o"
	@echo "... src/util/getopt.i"
	@echo "... src/util/getopt.s"
	@echo "... src/util/list.o"
	@echo "... src/util/list.i"
	@echo "... src/util/list.s"
	@echo "... src/util/log.o"
	@echo "... src/util/log.i"
	@echo "... src/util/log.s"
	@echo "... src/util/memory.o"
	@echo "... src/util/memory.i"
	@echo "... src/util/memory.s"
	@echo "... src/util/misc.o"
	@echo "... src/util/misc.i"
	@echo "... src/util/misc.s"
	@echo "... src/util/rbtree.o"
	@echo "... src/util/rbtree.i"
	@echo "... src/util/rbtree.s"
	@echo "... src/util/threads.o"
	@echo "... src/util/threads.i"
	@echo "... src/util/threads.s"
	@echo "... src/util/tiger.o"
	@echo "... src/util/tiger.i"
	@echo "... src/util/tiger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

